# Scene 4: Friend of a Foe

label s4_start:
    "I considered going to talk to Alyssa immediately. But I decided let Queen Maeve's message reach her first."
    "I stopped for my office, but I felt distracted and so went out, looking for little tasks to keep myself busy."
    otherwife "Hey, Sylvie, could I speak with you?"
    "It was Alyssa's partner. I didn't talk to her very often, but she seemed nice in those times."
    mc "Viola? I wasn't expecting this, but I can talk."
    otherwife "I thought I could say some things for Alyssa."
    mc "You don't think she can say them herself?"
    otherwife "It might go a little better if someone who was not feeling fire was part of the conversation."
    mc "And I am... I definitely was feeling fire. Let's try it."
    # "no-escalation"
    otherwife "Thank-you, I hope you two can work it out and get along, I don't want Alyssa to be hated."
    mc "Can you make that happen?"
    otherwife "I can try, if you will let me."
    mc "You can try and I hope you succeed, but... What did Alyssa tell you about what happened?"
    otherwife "She said you two got into a big fight about the weather on Long Night, she wanted the blizzard and you wanted to do nothing."
    mc "I wanted to let it be a clear night. And it does mean we have less to do."
    # "blizzard-last-year"
    mc "I'm not eager for another blizzard after the big one last year."
    otherwife "Last year was a big one wasn't it? I don't think Alyssa is pushing for one like that."
    mc "But it is still another blizzard."
    otherwife "It is it is something of a tradition."
    mc "I know, but we don't have to have one every year. In fact we never have done one every year."
    otherwife "Why do you want to skip the blizzard this year?"
    mc "There is nothing special about this year. That also means: Why have a blizzard this year? Even if it is a tradition."
    otherwife "Blizzards can be nice."
    mc "They can be. But do they have to be on Long Night? Do you want there to be a blizzard on Long Night?"
    otherwife "Yes. Maybe it is no surprise that Alyssa and I have some traditions around the Long Night blizzard."
    # "other-likes-snow" | "likes-snow"
    otherwife "She is always excited for dancing in the falling snow or even just relaxing in freshly fallen snow."
    mc "It is almost hard to imagine Alyssa being really excited for something."
    otherwife "Oh she tries not to show it, but she gets all giddy about it and it is adorable."
    otherwife "I am getting distracted."
    mc "A little bit."
    otherwife "Moving on. She also enjoys all the little traditions that remind her of all happy memories."
    mc "It is nice that she is happy, but it is a lot of work for everyone."
    otherwife "I know, weather my main job. Snow, wind, clouds."
    mc "So you should understand the down side of a blizzard."
    # "work-for-blizzard"
    otherwife "I know, I've put in more than one hard day of work on for a blizzard. And that is on top what we do for a regular snowfall."
    otherwife "And she knows that. She has helped us with it many times."
    mc "I have too. Most people have. And Alyssa has always has been happy to."
    otherwife "She will always put in the work. And we have to have storms at some point, so the work is not for nothing."
    mc "True, but it just feels worse on Long Night."
    otherwife "That's fair. But I hope you can see why Alyssa's position is also fair?"
    mc "I guess... but it is also how she..."
    mc "It is going to take more than her not being completely unreasonable to go with the blizzard again."
    otherwife "That is for you two to figure out, I can't help with that part."
    mc "Did you get the message from Queen Maeve?"
    otherwife "I was with Alyssa when she got it."
    mc "That's good."
    mc "Time to stop putting this off then."
    otherwife "Blessings to both of you."
    mc "Blessings to you to."
    jump s4_end

label s4_end:
    jump test
