# Scene 5: Showdown

label s5_start:
    "This time it was my turn to go to Alyssa. I went to her office, just like she had come to mine."
    mc "Hello, Alyssa, I've come to talk about the weather."
    other "Sylvie, I was- Could I have a moment to finish up?"
    mc "Of course."
    "I realized I might have caught her off guard. But she didn't ask me to leave."
    other "So, the weather."
    mc "Yes, well, um... I guess you heard from Queen Maeve."
    other "I did. Do you want to talk through the whole thing now?"
    mc "I don't have anything else I can do to prepare."
    other "I have already said why I think we should have the Long Night blizzard."
    mc "Because it is a grand tradition. While I don't want everyone to have to work on the day of Long Night."
    other "Is there anything else we need to cover?"
    mc "Did you read the rest of my notes on the plans for the weather?"
    other "I did, there was nothing in that changed my mind, but no other problems."
    mc "We are back where we started then."
    other "Do you have nothing else to add to your case?"
    mc "Just, it is a tradition and we put a blizzard on Long Night the years it makes sense, but we don't have to. We have skipped years before."
    other "It is a tradition for a reason, who wouldn't like wind and falling snow for Long Night."
    # "other-likes-snow"
    mc "It feels like this is more about the snow than the blizzard."
    other "Yes, I love snow! I love watching it fall and flying out in the snow fall. Everyone knows about it!"
    other "People always seem to make a joke about how that doesn't suit me."
    mc "I wouldn't- I don't- You can like the snow if you want. It's fine."
    other "That's good. But that isn't the reason I think we should have the blizzard."
    mc "Not even a little."
    other "Long Night only comes once a year and it is the big night of the year. If there is one time for extra effort in the weather, it is then."
    mc "Why does that mean a blizzard?"
    other "Take a moment Sylvie, and think about your most iconic Long Night memories. What is the weather like?"
    mc "So, I see what you mean, it is the classic image, but I still have plenty of happy memories from clear Long Night."
    other "It does bring that little something extra to it if you put in the extra work."
    # "mc-wants-holiday"
    mc "But it isn't just the work, it is the time."
    other "And what is the practical difference between those two?"
    mc "Because it is time spent on Long Night, a night were absolutely everyone has something to look forward to when they get home."
    other "Last time was really bad, but that was just some bad planning, most of the time it is much better."
    mc "Usually it is still longer than usual."
    mc "I mean, most blizzards still mean people are putting in extra time to make them happen."
    other "True, but we have to do that work eventually. Even if we don't have the blizzard on Long Night, we have to do that work eventually."
    # "different-weather"
    mc "But do we have to go all the way to a blizzard?"
    other "What do you mean by that?"
    mc "Maeve said we can decide on any weather that could have been picked from the start. The options are not just a clear night or massive blizzard."
    other "Right, that makes sense. So if we want some Long Night weather, we can go for something else."
    mc "'We' want Long Night weather?"
    other "I want some Long Night weather, you want a good time frame, so we want both of those things."
    mc "Fair enough."
    other "Instead of a blizzard, we could do a snow-storm. No, cut the wind entirely, a large amount of snow will do."
    mc "Is a heavy snow fall close enough to a blizzard?"
    other "Imagine it, take a moment to picture a night filled with snow. Does that feel like Long Night?"
    mc "It is good enough for me, but you are the one who is worried about it."
    other "I think it feels like Long Night."
    mc "Could we do just a heavy snow-fall instead of a blizzard? It is almost the same thing with less wind."
    other "People should enjoy that, and it will be easier to set up."
    mc "Are we in agreement?"
    other "Yes, we are."
    mc "Now, we just have to tell Maeve and make sure it goes into the final schedule."
    other "We can go tell Queen Maeve right now."
    mc "Then let's go."
    jump s5_end

label s5_end:
    jump end_of_game
